### ISSUE TITLE
Request for new attributes for SoSEn

### ISSUE THREAD

**Issue by AidanKelley** [KnowledgeCaptureAndDiscovery/SoftwareDescriptionOntology#15]
Could the following be added?

* sd:executionInstructions
* sd:downloadInstructions
* sd:contactDetails
* sd:contributionInstructions
* sd:doi

**Comment by AidanKelley** [comment]
also,
sd:softwareCitation

**Comment by AidanKelley** [comment]
not sd:softwareCitation, we should actually add sd:preferredCitation (I think this does not currently exist)

**Comment by dgarijo** [comment]
We have https://w3id.org/okn/o/sd#referencePublication and sd:citation, so I think we are fine.
referencePublilcation is the main one, so it should be used as the one identified by authors

**Comment by dgarijo** [comment]
ContactDetails may not be needed, because we have email and description of person.

**Comment by dgarijo** [comment]
Fixed in https://github.com/KnowledgeCaptureAndDiscovery/SoftwareDescriptionOntology/commit/9f2b740a8a936226206fc109d853086812bb5fbe
