### ISSUE TITLE
Properties with undefined range

### ISSUE THREAD

**Issue by mosoriob** [KnowledgeCaptureAndDiscovery/SoftwareDescriptionOntology#5]
The following properties have an undefined range

https://w3id.org/okn/o/sd#hasFileStructure 
https://w3id.org/okn/o/sd#hasFixedValue
https://w3id.org/okn/o/sd#hasDefaultValue
https://w3id.org/okn/o/sd#hasMinimumAcceptedValue 
https://w3id.org/okn/o/sd#hasMaximumAcceptedValue

**Comment by dgarijo** [comment]
This is not a bug for the most part :)
For example, hasFixedValue hasDefaultValue, etc. can have range int, bool float or string. 
And hasFileStructure is a placeholder for the table understanding software that we have yet to test.

**Comment by mosoriob** [comment]
![image](https://user-images.githubusercontent.com/2365990/64349222-91502880-cfc4-11e9-8bb0-855f746c8714.png)
